In [1]:
import pandas as pd
import numpy as np

In [2]:
df_2017 = pd.read_excel('Fires_100.xlsx')

In [3]:
df_2016 = pd.read_excel('Fires_100.xlsx',1)

In [4]:
df_2017.head(5)

,YEAR_,STATE,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,ALARM_DATE,CONT_DATE,CAUSE,COMMENTS,REPORT_AC,GIS_ACRES,C_METHOD,OBJECTIVE
0,2017,California,California Department of Forestry and Fire Pro...,Tulare County,DINELY,286,2017-06-07,2017-06-11,2 - Equipment Use,<Null>,339,340.5638,1 - GPS Ground,Suppression (Wildfire)
1,2017,California,California Department of Forestry and Fire Pro...,Tulare County,ROADRUNNER,441,2017-07-30,2017-08-01,7 - Arson,<Null>,2289,2284.5960,1 - GPS Ground,Suppression (Wildfire)
2,2017,California,California Department of Forestry and Fire Pro...,Tulare County,ELEPHANT 2,420,2017-07-20,2017-07-22,7 - Arson,<Null>,416,415.2116,1 - GPS Ground,Suppression (Wildfire)
3,2017,California,California Department of Forestry and Fire Pro...,Tehama - Glenn CAL FIRE,TEHAMA,10345,2017-10-30,2017-10-31,10 - Vehicle,<Null>,194,194.0017,1 - GPS Ground,Suppression (Wildfire)
4,2017,California,California Department of Forestry and Fire Pro...,Tuolumne - Calaveras CAL FIRE,JACKSONVILLE,9024,2017-07-29,2017-07-30,14 - Unknown / Unidentified,<Null>,<Null>,684.3565,1 - GPS Ground,Suppression (Wildfire)

In [5]:
df_2017.rename(columns={'YEAR_':'YEAR'}, inplace=True)
df_2017.YEAR.fillna(2017, inplace=True)

In [6]:
df_2016 = df_2016[df_2016.YEAR!='<Null>'].dropna(subset='YEAR')

In [7]:
df_2016.tail(5)

,YEAR,STATE,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,ALARM_DATE,CONT_DATE,CAUSE,COMMENTS,REPORT_AC,GIS_ACRES,C_METHOD,OBJECTIVE
11728,2016,California,California Department of Forestry and Fire Pro...,Santa Clara CAL FIRE,DIABLO,5693,2016-08-02 00:00:00,2016-08-02 00:00:00,14 - Unknown / Unidentified,NaN,25,101.0175,2 - GPS Air,Suppression (Wildfire)
11729,2016,California,California Department of Forestry and Fire Pro...,Santa Clara CAL FIRE,LOMA,6912,2016-09-26 00:00:00,2016-10-26 00:00:00,14 - Unknown / Unidentified,NaN,2000,4474.1240,2 - GPS Air,Suppression (Wildfire)
11730,2016,California,California Department of Forestry and Fire Pro...,Santa Clara CAL FIRE,SIERRA,5839,2016-07-30 00:00:00,2016-08-01 00:00:00,2 - Equipment Use,NaN,50,123.9659,2 - GPS Air,Suppression (Wildfire)
11731,2016,California,California Department of Forestry and Fire Pro...,Amador - El Dorado CAL FIRE,CAMANCHE,16373,2016-06-17 00:00:00,2016-06-19 00:00:00,14 - Unknown / Unidentified,<Null>,201,209.5521,1 - GPS Ground,Suppression (Wildfire)
11732,2016,California,California Department of Forestry and Fire Pro...,Amador - El Dorado CAL FIRE,RANCHO,17670,2016-06-28 00:00:00,2016-06-29 00:00:00,10 - Vehicle,<Null>,372,371.6552,1 - GPS Ground,Suppression (Wildfire)

In [8]:
df_2016.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11733 entries, 0 to 11732
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   YEAR        11733 non-null  object
 1   STATE       11733 non-null  object
 2   AGENCY      11733 non-null  object
 3   UNIT_ID     11732 non-null  object
 4   FIRE_NAME   11707 non-null  object
 5   INC_NUM     11658 non-null  object
 6   ALARM_DATE  11733 non-null  object
 7   CONT_DATE   11733 non-null  object
 8   CAUSE       11733 non-null  object
 9   COMMENTS    1905 non-null   object
 10  REPORT_AC   11733 non-null  object
 11  GIS_ACRES   11733 non-null  float64
 12  C_METHOD    11733 non-null  object
 13  OBJECTIVE   11733 non-null  object
dtypes: float64(1), object(13)
memory usage: 1.3+ MB

In [9]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   YEAR        182 non-null    int64
 1   STATE       182 non-null    object
 2   AGENCY      182 non-null    object
 3   UNIT_ID     182 non-null    object
 4   FIRE_NAME   182 non-null    object
 5   INC_NUM     182 non-null    int64
 6   ALARM_DATE  182 non-null    datetime64[ns]
 7   CONT_DATE   182 non-null    datetime64[ns]
 8   CAUSE       182 non-null    object
 9   COMMENTS    160 non-null    object
 10  REPORT_AC   182 non-null    object
 11  GIS_ACRES   182 non-null    float64
 12  C_METHOD    182 non-null    object
 13  OBJECTIVE   182 non-null    object
dtypes: datetime64[ns](2), float64(1), int64(2), object(9)
memory usage: 20.0+ KB

In [10]:
df = pd.concat([df_2016, df_2017])

In [11]:
df.head()

,YEAR,STATE,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,ALARM_DATE,CONT_DATE,CAUSE,COMMENTS,REPORT_AC,GIS_ACRES,C_METHOD,OBJECTIVE
0,1878,California,Contract County,Los Angeles County,,0,<Null>,<Null>,14 - Unknown / Unidentified,NaN,<Null>,59468.8800,<Null>,Suppression (Wildfire)
1,1895,California,Contract County,Los Angeles County,,0,<Null>,<Null>,14 - Unknown / Unidentified,NaN,<Null>,628.1136,<Null>,Suppression (Wildfire)
2,1896,California,Contract County,Los Angeles County,,0,<Null>,<Null>,14 - Unknown / Unidentified,NaN,<Null>,7531.7170,<Null>,Suppression (Wildfire)
3,1898,California,Contract County,Los Angeles County,,0,<Null>,<Null>,14 - Unknown / Unidentified,NaN,<Null>,1660.1030,<Null>,Suppression (Wildfire)
4,1898,California,Contract County,Los Angeles County,,0,<Null>,<Null>,14 - Unknown / Unidentified,NaN,<Null>,428.4387,<Null>,Suppression (Wildfire)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11915 entries, 0 to 181
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   YEAR        11915 non-null  object
 1   STATE       11915 non-null  object
 2   AGENCY      11915 non-null  object
 3   UNIT_ID     11914 non-null  object
 4   FIRE_NAME   11889 non-null  object
 5   INC_NUM     11840 non-null  object
 6   ALARM_DATE  11915 non-null  object
 7   CONT_DATE   11915 non-null  object
 8   CAUSE       11915 non-null  object
 9   COMMENTS    2065 non-null   object
 10  REPORT_AC   11915 non-null  object
 11  GIS_ACRES   11915 non-null  float64
 12  C_METHOD    11915 non-null  object
 13  OBJECTIVE   11915 non-null  object
dtypes: float64(1), object(13)
memory usage: 1.4+ MB

In [13]:
df.columns

Index(['YEAR', 'STATE', 'AGENCY', 'UNIT_ID', 'FIRE_NAME', 'INC_NUM',
       'ALARM_DATE', 'CONT_DATE', 'CAUSE', 'COMMENTS', 'REPORT_AC',
       'GIS_ACRES', 'C_METHOD', 'OBJECTIVE'],
      dtype='object')

In [14]:
df = df[['YEAR', 'AGENCY', 'UNIT_ID', 'FIRE_NAME', 'INC_NUM',
       'ALARM_DATE', 'CONT_DATE', 'CAUSE', 'REPORT_AC',
       'GIS_ACRES', 'C_METHOD', 'OBJECTIVE']]

In [15]:
df = df.replace('<Null>', np.nan)
df.to_csv('wildfires.csv', index=False)

In [16]:
df = pd.read_csv('wildfires.csv', parse_dates=True)
df

,YEAR,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,ALARM_DATE,CONT_DATE,CAUSE,REPORT_AC,GIS_ACRES,C_METHOD,OBJECTIVE
0,1878,Contract County,Los Angeles County,,0,NaN,NaN,14 - Unknown / Unidentified,NaN,59468.8800,NaN,Suppression (Wildfire)
1,1895,Contract County,Los Angeles County,,0,NaN,NaN,14 - Unknown / Unidentified,NaN,628.1136,NaN,Suppression (Wildfire)
2,1896,Contract County,Los Angeles County,,0,NaN,NaN,14 - Unknown / Unidentified,NaN,7531.7170,NaN,Suppression (Wildfire)
3,1898,Contract County,Los Angeles County,,0,NaN,NaN,14 - Unknown / Unidentified,NaN,1660.1030,NaN,Suppression (Wildfire)
4,1898,Contract County,Los Angeles County,,0,NaN,NaN,14 - Unknown / Unidentified,NaN,428.4387,NaN,Suppression (Wildfire)
...,...,...,...,...,...,...,...,...,...,...,...,...
11910,2017,National Park Service,Yosemite National Park,SOUTH FORK,108,2017-08-13 00:00:00,2017-11-03,1 - Lightning,7000.0,7560.0770,8 - Unknown,Suppression (Wildfire)
11911,2017,California Department of Forestry and Fire Pro...,Sonoma - Lake - Napa CAL FIRE,REDWOOD VALLEY,12172,2017-10-08 00:00:00,2017-10-25,14 - Unknown / Unidentified,NaN,36522.9500,8 - Unknown,Suppression (Wildfire)
11912,2017,USDA Forest Service,Rouge River- Siskiyou,ABNEY,568,2017-08-10 00:00:00,2018-01-10,1 - Lightning,NaN,32893.2600,8 - Unknown,Suppression (Wildfire)
11913,2017,USDA Forest Service,Rouge River- Siskiyou,KNOX,612,2017-08-11 00:00:00,2017-11-28,1 - Lightning,NaN,492.5997,8 - Unknown,Suppression (Wildfire)
11914,2017,Department of Defense,Camp Pendleton Marine Corps Base,CRISTIANITOS,1702047,2017-06-28 00:00:00,2017-06-30,9 - Miscellaneous,NaN,702.3066,5 - Photo Interpretation,Suppression (Wildfire)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11915 entries, 0 to 11914
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   YEAR        11915 non-null  int64
 1   AGENCY      11915 non-null  object
 2   UNIT_ID     11912 non-null  object
 3   FIRE_NAME   11887 non-null  object
 4   INC_NUM     11495 non-null  object
 5   ALARM_DATE  7992 non-null   object
 6   CONT_DATE   3156 non-null   object
 7   CAUSE       11904 non-null  object
 8   REPORT_AC   3594 non-null   float64
 9   GIS_ACRES   11915 non-null  float64
 10  C_METHOD    3478 non-null   object
 11  OBJECTIVE   11859 non-null  object
dtypes: float64(2), int64(1), object(9)
memory usage: 1.1+ MB

In [20]:
len(df.UNIT_ID.unique())

80